#!/usr/bin/env node
/**
 * Pre-computes land dot positions for the globe and writes dots.js.
 * Run once: node generate-dots.mjs
 *
 * Requires: npm install topojson-client d3-geo node-fetch
 */

import { createRequire } from 'module';
import { writeFileSync } from 'fs';

const require = createRequire(import.meta.url);

let feature, geoContains, fetch;

try {
  ({ feature } = await import('topojson-client'));
  ({ geoContains } = await import('d3-geo'));
  ({ default: fetch } = await import('node-fetch'));
} catch {
  console.error('Missing dependencies. Run:\n  npm install topojson-client d3-geo node-fetch');
  process.exit(1);
}

console.log('Fetching world-atlas data…');
const topo = await fetch('https://cdn.jsdelivr.net/npm/world-atlas@2/land-110m.json').then(r => r.json());
const land = feature(topo, topo.objects.land);

const DOT_COUNT = 2000;
const positions = [];

function coastScore(lon, lat) {
  const dist = 6.0;
  const dirs = [[dist,0],[-dist,0],[0,dist],[0,-dist],[dist,dist],[-dist,dist],[dist,-dist],[-dist,-dist]];
  let sea = 0;
  for (const [dl, dp] of dirs) {
    if (!geoContains(land, [lon + dl, lat + dp])) sea++;
  }
  return sea / dirs.length;
}

console.log(`Placing ${DOT_COUNT} dots…`);
let placed = 0;
let attempts = 0;
while (placed < DOT_COUNT) {
  attempts++;
  const theta = 2 * Math.PI * Math.random();
  const phi   = Math.acos(2 * Math.random() - 1);
  const lon   = 180 - theta * (180 / Math.PI);
  const lat   = 90 - phi * (180 / Math.PI);
  if (!geoContains(land, [lon, lat])) continue;
  const score = coastScore(lon, lat);
  if (Math.random() > 0.02 + 0.98 * score) continue;
  const r = 1.002;
  positions.push(
    r * Math.sin(phi) * Math.cos(theta),
    r * Math.cos(phi),
    r * Math.sin(phi) * Math.sin(theta),
  );
  placed++;
  if (placed % 200 === 0) process.stdout.write(`  ${placed}/${DOT_COUNT}\r`);
}

console.log(`\nDone — ${attempts} attempts for ${DOT_COUNT} dots.`);

const floats = positions.map(v => v.toFixed(6));
const output = `// Auto-generated by generate-dots.mjs — do not edit by hand.
// ${DOT_COUNT} pre-computed land dot positions (x, y, z interleaved).
export const DOT_POSITIONS = new Float32Array([
  ${floats.join(', ')}
]);
`;

writeFileSync(new URL('./dots.js', import.meta.url), output);
console.log('Wrote dots.js');
